# Define o ambiente de execução como Python 3.11 (ajuste se necessário)
runtime: python313

# O ponto de entrada da sua aplicação. Usa o Gunicorn, um servidor WSGI de produção.
entrypoint: gunicorn -b :$PORT app:app

# Configuração para escalonamento automático.
automatic_scaling:
  min_instances: 0
  max_instances: 1

# --- NOVA CONFIGURAÇÃO PARA AUMENTAR O TEMPO DE ARRANQUE ---
readiness_check:
  app_start_timeout_sec: 300 # Aumenta o tempo de espera para 5 minutos

# AQUI VOCÊ COLOCA AS SUAS VARIÁVEIS DE AMBIENTE
# O App Engine irá injetá-las na sua aplicação quando ela estiver online.
# SUBSTITUA OS VALORES DE EXEMPLO PELOS SEUS.
env_variables:
  DB_USER: "postgres"
  DB_PASS: "Transcicaotmb@_2025"
  DB_NAME: "postgres" # Ou o nome que você usou
  INSTANCE_CONNECTION_NAME: "transcricao-467718:southamerica-east1:tmb-db-instance"
  GCS_BUCKET_NAME: "meus-ficheiros-de-audio-viini"
